######################## default configuration ####################
baseurl = "https://deeplearning.earth/"
title = "Deep Learning 4 Earth"
theme = "godocs-3"
# google analytics
googleAnalytics = "" # example : UA-123-45
# disable language
disableLanguages = [] # disable language from here

# hugo outputs
[outputs]
home = [ "HTML", "JSON"]

# render unsafe html
[markup.goldmark.renderer]
unsafe = true

# table of content
[markup.tableOfContents]
startLevel = 0
endLevel = 6
ordered = false

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
attributes = "media='screen'"
page = "/"

[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
attributes = ""
page = "/"

[[params.plugins.css]]
link = "plugins/search/auto-complete.css"
attributes = ""
page = "/"

[[params.plugins.css]]
link = "plugins/featherlight/featherlight.min.css"
attributes = ""
page = "/"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
attributes = ""
page = "/"

[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
attributes = ""
page = "/"

[[params.plugins.js]]
link = "plugins/turbolinks/turbolinks.js"
attributes = ""
page = "/"

[[params.plugins.js]]
link = "plugins/masonry/masonry.min.js"
attributes = ""
page = "/"

[[params.plugins.js]]
link = "plugins/featherlight/featherlight.min.js"
attributes = ""
page = "/"

[[params.plugins.js]]
link = "plugins/clipboard/clipboard.min.js"
attributes = ""
page = "/"

[[params.plugins.js]]
link = "plugins/scrollmenu/scrollmenu.min.js"
attributes = ""
page = "/"

[[params.plugins.js]]
link = "plugins/search/auto-complete.js"
attributes = ""
page = "/"

[[params.plugins.js]]
link = "plugins/search/search.js"
attributes = ""
page = "/"

[[params.plugins.js]]
link = "plugins/search/lunr.min.js"
attributes = ""
page = "/"


############## English navigation ###############

# main menu
[[Languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1

[[Languages.en.menu.main]]
name = "Detection"
url = "/detection"
weight = 2

[[Languages.en.menu.main]]
name = "Resources"
url = "/resources"
weight = 3

# footer menu
[[Languages.en.menu.footer]]
name = "Fork me on Github"
url = "https://github.com/jeffaudi/deeplearning.earth"
weight = 1


############## French navigation ###############

# main menu
[[Languages.fr.menu.main]]
name = "Home"
url = "/"
weight = 1

[[Languages.fr.menu.main]]
name = "Detection"
url = "/detection"
weight = 2

[[Languages.fr.menu.main]]
name = "Ressources"
url = "/resources"
weight = 3

# footer menu
[[Languages.fr.menu.footer]]
name = "Editez sur Github"
url = "https://github.com/jeffaudi/deeplearning.earth"
weight = 1


#################### default parameters ################################
[params]
logo = "img/logo.png"

# Meta data
description = "This is meta description"
author = "Jeff Faudi"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# table of content on document page
table_of_content = true

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[[params.nav_button]]
style = "outline" # available style: solid, outline
label = "About"
link = "/about"

[[params.nav_button]]
style = "solid" # available style: solid, outline
label = "Contact"
link = "contact"


############################# social site ########################

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/jeffaudi"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/jeffaudi"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/in/faudi/"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
# copyright
copyright = "&copy; 2021 Jeff Faudi and al."
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

# call to action
[Languages.en.call_to_action]
enable = true
title = "Looking for something specific?"
#image = "images/cta-illustration.jpg"
content = "Please, reach out to me if you would like a specific topic to be addressed here!"

  # call to action button
  [Languages.en.call_to_action.button]
  enable = "true"
  label = "Reach out"
  link = "contact"


################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
weight = 2
# copyright
copyright = "&copy; 2021 Jeff Faudi and al."

# call to action
[Languages.fr.call_to_action]
enable = true
title = "Vous rechercher autre chose?"
#image = "images/cta-illustration.jpg"
content = "N'hésitez pas à me contacter pour me proposer d'autres sujets !"

  # call to action button
  [Languages.fr.call_to_action.button]
  enable = "true"
  label = "Contactez moi"
  link = "contact"
  
